name: Build and Push peak-app + peak-nginx to GHCR

on:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  REPO: hike

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract short SHA
      id: vars
      run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

    - name: Read version from VERSION file
      id: version
      run: echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"

    - name: Build and push peak-app image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPO }}/peak-app:${{ steps.version.outputs.version }}-${{ steps.vars.outputs.short_sha }}
          ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPO }}/peak-app:latest

    - name: Build and push peak-nginx image
      uses: docker/build-push-action@v5
      with:
        context: ./nginx
        file: ./nginx/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPO }}/peak-nginx:${{ steps.version.outputs.version }}-${{ steps.vars.outputs.short_sha }}
          ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPO }}/peak-nginx:latest